name: Run Tests

on:
  push:
#    branches:
#      - master
    paths:
      - '**.go'
      - 'go.*'
      - '_fixture/**'
      - '.github/**'
      - 'codecov.yml'
  pull_request:
    branches:
      - master
    paths:
      - '**.go'
      - 'go.*'
      - '_fixture/**'
      - '.github/**'
      - 'codecov.yml'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [1.17]
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Run Tests
        run: |
          make
